### ISSUE TITLE
Video codec hevc not compatible with flv!

### ISSUE THREAD

**Issue by benpar2** [runner365/ffmpeg_rtmp_h265#2]
I compiled ffmpeg with libx265 based on your instruction, but when I tried to push hevc stream through rtmp, I faced with this error;

```
[flv @ 0x563fe9051c80] Video codec hevc not compatible with flv
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Error initializing output stream 0:0 -- 
```

How can I send hevc stream by rtmp and flv?
thanks.

**Comment by nohairdave** [comment]
I'm seeing this issue - what was the fix?
